### ISSUE TITLE
Running gmt grdinfo on netcdf files causes error: "gmt: error while loading shared libraries: libLerc.so.4: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by mhearne-usgs** [conda-forge/gmt-feedstock#221] opened 2022-10-31 18:54 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Running gmt grdinfo on netcdf files causes error: "gmt: error while loading shared libraries: libLerc.so.4: cannot open shared object file: No such file or directory"

### Installed packages

```shell
# packages in environment at /home/mhearne/miniconda/envs/testenv:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
affine                    2.3.1                    pypi_0    pypi
asttokens                 2.1.0                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
black                     22.10.0                  pypi_0    pypi
blosc                     1.21.1               h83bc5f7_3    conda-forge
boost-cpp                 1.78.0               h75c5d50_1    conda-forge
bzip2                     1.0.8                h7b6447c_0
c-ares                    1.18.1               h7f8727e_0
ca-certificates           2022.10.11           h06a4308_0
cairo                     1.16.0               h19f5f5c_2
certifi                   2022.9.24        py39h06a4308_0
cfitsio                   4.1.0                hd9d235c_0    conda-forge
cftime                    1.6.2                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
click-plugins             1.1.1                    pypi_0    pypi
cligj                     0.7.2                    pypi_0    pypi
coverage                  6.5.0                    pypi_0    pypi
curl                      7.85.0               h5eee18b_0
dcw-gmt                   2.1.1                ha770c72_0    conda-forge
decorator                 5.1.1                    pypi_0    pypi
esi-utils-io              1.0.2                    pypi_0    pypi
exceptiongroup            1.0.0                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
expat                     2.4.9                h6a678d5_0
fftw                      3.3.10          nompi_hf0379b8_105    conda-forge
flake8                    5.0.4                    pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hd3eb1b0_0
font-ttf-inconsolata      2.001                hcb22688_0
font-ttf-source-code-pro  2.030                hd3eb1b0_0
font-ttf-ubuntu           0.83                 h8b1ccd4_0
fontconfig                2.14.1               hc2a2eb6_0    conda-forge
fonts-anaconda            1                    h8fa9717_0
fonts-conda-ecosystem     1                    hd3eb1b0_0
freetype                  2.12.1               h4a9f257_0
freexl                    1.0.6                h27cfd23_0
gdal                      3.5.2            py39haa391fb_0    conda-forge
geographiclib             1.52                     pypi_0    pypi
geopy                     2.2.0                    pypi_0    pypi
geos                      3.11.0               h27087fc_0    conda-forge
geotiff                   1.7.1                h4fc65e6_3    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
ghostscript               9.54.0               h27087fc_2    conda-forge
giflib                    5.2.1                h7b6447c_0
glib                      2.74.1               h6239696_0    conda-forge
glib-tools                2.74.1               h6239696_0    conda-forge
gmt                       6.4.0                h78e8b95_2    conda-forge
gshhg-gmt                 2.3.7             ha770c72_1003    conda-forge
h5py                      3.7.0                    pypi_0    pypi
hdf4                      4.2.15               h9772cbc_5    conda-forge
hdf5                      1.12.2          nompi_h2386368_100    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
iniconfig                 1.1.1                    pypi_0    pypi
ipython                   8.6.0                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jpeg                      9e                   h7f8727e_0
json-c                    0.16                 h5eee18b_0
kealib                    1.4.15               ha7026e8_1    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.38                 h1181459_1
lerc                      3.0                  h295c915_0
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.85.0               h91b91d3_0
libdap4                   3.20.6               hd7c4107_2    conda-forge
libdeflate                1.8                  h7f8727e_5
libedit                   3.1.20210910         h7f8727e_0
libev                     4.33                 h7f8727e_1
libffi                    3.4.2                h295c915_4
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgdal                   3.5.2                hc23bfc3_0    conda-forge
libgfortran-ng            11.2.0               h00389a5_1
libgfortran5              11.2.0               h1234567_1
libglib                   2.74.1               h7a41b64_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libkml                    1.3.0             h37653c0_1015    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnetcdf                 4.8.1           nompi_h261ec11_105    conda-forge
libnghttp2                1.46.0               hce63b2e_0
libnsl                    2.0.0                h5eee18b_0
libopenblas               0.3.21               h043d6bf_0
libpng                    1.6.37               hbc83047_0
libpq                     14.5                 hd77ab85_1    conda-forge
librttopo                 1.1.0               hf730bdb_11    conda-forge
libspatialite             5.0.1               hd36657c_19    conda-forge
libsqlite                 3.39.4               h753d276_0    conda-forge
libssh2                   1.10.0               h8f2d780_0
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.4.0                hecacb30_0
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.4                h5eee18b_0
libxcb                    1.15                 h7f8727e_0
libxml2                   2.10.3               h7463322_0    conda-forge
libzip                    1.9.2                hc869a4a_1    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvm-openmp               14.0.6               h9e868ea_0
lz4-c                     1.9.3                h295c915_1
mapio                     1.2.0                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mccabe                    0.7.0                    pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3
netcdf4                   1.6.1                    pypi_0    pypi
nspr                      4.33                 h295c915_0
nss                       3.78                 h2350873_0    conda-forge
numpy                     1.23.4           py39h3d75532_1    conda-forge
openjpeg                  2.5.0                h7d73246_1    conda-forge
openssl                   1.1.1q               h7f8727e_0
packaging                 21.3                     pypi_0    pypi
pandas                    1.5.1                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathspec                  0.10.1                   pypi_0    pypi
pcre                      8.45                 h295c915_0
pcre2                     10.37                he7ceb23_1
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       22.2.2           py39h06a4308_0
pixman                    0.40.0               h7f8727e_1
platformdirs              2.5.2                    pypi_0    pypi
pluggy                    1.0.0                    pypi_0    pypi
poppler                   22.04.0              h0733791_3    conda-forge
poppler-data              0.4.11               h06a4308_0
postgresql                14.5                 hdeef612_1    conda-forge
proj                      9.0.1                h93bde94_1    conda-forge
prompt-toolkit            3.0.31                   pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pycodestyle               2.9.1                    pypi_0    pypi
pyflakes                  2.5.0                    pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyproj                    3.4.0                    pypi_0    pypi
pytest                    7.2.0                    pypi_0    pypi
pytest-console-scripts    1.3.1                    pypi_0    pypi
pytest-cov                4.0.0                    pypi_0    pypi
python                    3.9.13          h9a8a25e_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.5                   pypi_0    pypi
rasterio                  1.3.3                    pypi_0    pypi
readline                  8.2                  h5eee18b_0
scipy                     1.9.3                    pypi_0    pypi
setuptools                65.4.0           py39h06a4308_0
shapely                   1.8.5.post1              pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
snappy                    1.1.9                h295c915_0
snuggs                    1.4.7                    pypi_0    pypi
sqlite                    3.39.3               h5082296_0
stack-data                0.6.0                    pypi_0    pypi
tiledb                    2.11.3               h1e4a385_1    conda-forge
tk                        8.6.12               h1ccaba5_0
tomli                     2.0.1                    pypi_0    pypi
traitlets                 5.5.0                    pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
tzcode                    2022e                h166bdaf_0    conda-forge
tzdata                    2022e                h04d1e81_0
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
xerces-c                  3.2.4                h55805fa_1    conda-forge
xz                        5.2.6                h5eee18b_0
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                ha4553b6_0
```

### Environment info

```shell
active environment : testenv
    active env location : /home/mhearne/miniconda/envs/testenv
            shell level : 2
       user config file : /home/mhearne/.condarc
 populated config files : /home/mhearne/.condarc
          conda version : 4.14.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __cuda=11.6=0
                          __linux=5.10.16.3=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/mhearne/miniconda  (writable)
      conda av data dir : /home/mhearne/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/mhearne/miniconda/pkgs
                          /home/mhearne/.conda/pkgs
       envs directories : /home/mhearne/miniconda/envs
                          /home/mhearne/.conda/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.28.1 CPython/3.9.7 Linux/5.10.16.3-microsoft-standard-WSL2 ubuntu/20.04.4 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by ocefpaf** [comment] 2022-10-31 19:06
Looks like you are mixing defaults and conda-forge channels there. (All those pkgs that don't have `conda-forge` to the right are from defaults.)

**Comment by seisman** [comment] 2022-12-01 04:55
I'm closing the issue because there seems to be caused by the mixing channels and nothing can be fixed on our side.

**Closed by seisman** 2022-12-01 04:55 UTC
Labels: bug
